#!/usr/bin/env bash
#
# extract-amplify-outputs.sh
# Parses amplify_outputs.json and generates terraform.tfvars values
# for cognito_user_pool_id and athena_lambda_arn.
#
# The script reads amplify_outputs.json from the project root
# and writes/updates the corresponding values in infra/terraform.tfvars.
#
# Usage:
#   ./scripts/extract-amplify-outputs.sh
#
# Prerequisites:
#   - jq installed (brew install jq / apt-get install jq)
#   - amplify_outputs.json exists in the project root (generated by ampx pipeline-deploy)

set -euo pipefail

# ─── Configuration ─────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AMPLIFY_OUTPUTS="$PROJECT_ROOT/amplify_outputs.json"
TFVARS_FILE="$PROJECT_ROOT/infra/terraform.tfvars"
TFVARS_EXAMPLE="$PROJECT_ROOT/infra/terraform.tfvars.example"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ─── Prerequisite Checks ──────────────────────────────────────────────────────

if ! command -v jq &> /dev/null; then
  echo -e "${RED}ERROR: jq is required but not installed.${NC}"
  echo "  Install with: brew install jq (macOS) or apt-get install jq (Ubuntu)"
  exit 1
fi

if [ ! -f "$AMPLIFY_OUTPUTS" ]; then
  echo -e "${RED}ERROR: amplify_outputs.json not found at: $AMPLIFY_OUTPUTS${NC}"
  echo "  Run 'npx ampx pipeline-deploy' first to generate this file."
  exit 1
fi

# ─── Extract Values ────────────────────────────────────────────────────────────

echo "Extracting values from amplify_outputs.json..."

# Extract Cognito User Pool ID from auth section
COGNITO_USER_POOL_ID=$(jq -r '.auth.user_pool_id // .auth.userPoolId // empty' "$AMPLIFY_OUTPUTS" 2>/dev/null || true)

if [ -z "$COGNITO_USER_POOL_ID" ]; then
  echo -e "${YELLOW}WARNING: Could not extract cognito_user_pool_id from amplify_outputs.json${NC}"
  echo "  Checking alternate paths..."
  # Try alternate JSON paths that Amplify Gen 2 might use
  COGNITO_USER_POOL_ID=$(jq -r '.. | .user_pool_id? // empty' "$AMPLIFY_OUTPUTS" 2>/dev/null | head -1 || true)
fi

# Extract Athena Lambda ARN from custom/function section
ATHENA_LAMBDA_ARN=$(jq -r '.custom.athenaQueryFunctionArn // .custom.athena_query_function_arn // empty' "$AMPLIFY_OUTPUTS" 2>/dev/null || true)

if [ -z "$ATHENA_LAMBDA_ARN" ]; then
  echo -e "${YELLOW}WARNING: Could not extract athena_lambda_arn from amplify_outputs.json${NC}"
  echo "  Checking alternate paths..."
  # Try alternate JSON paths
  ATHENA_LAMBDA_ARN=$(jq -r '.. | .athenaQueryFunctionArn? // empty' "$AMPLIFY_OUTPUTS" 2>/dev/null | head -1 || true)
fi

# ─── Report Extracted Values ──────────────────────────────────────────────────

echo ""
echo "Extracted values:"
echo "  cognito_user_pool_id = ${COGNITO_USER_POOL_ID:-<not found>}"
echo "  athena_lambda_arn    = ${ATHENA_LAMBDA_ARN:-<not found>}"
echo ""

if [ -z "$COGNITO_USER_POOL_ID" ] && [ -z "$ATHENA_LAMBDA_ARN" ]; then
  echo -e "${RED}ERROR: Could not extract any values from amplify_outputs.json${NC}"
  echo "  Check the file structure and ensure the Amplify backend deployed correctly."
  exit 1
fi

# ─── Update terraform.tfvars ──────────────────────────────────────────────────

# If terraform.tfvars doesn't exist, copy from example
if [ ! -f "$TFVARS_FILE" ]; then
  if [ -f "$TFVARS_EXAMPLE" ]; then
    echo "  Creating terraform.tfvars from example..."
    cp "$TFVARS_EXAMPLE" "$TFVARS_FILE"
  else
    echo -e "${RED}ERROR: Neither terraform.tfvars nor terraform.tfvars.example found.${NC}"
    exit 1
  fi
fi

# Update cognito_user_pool_id in tfvars
if [ -n "$COGNITO_USER_POOL_ID" ]; then
  if grep -q "^cognito_user_pool_id" "$TFVARS_FILE"; then
    sed -i.bak "s|^cognito_user_pool_id.*|cognito_user_pool_id = \"$COGNITO_USER_POOL_ID\"|" "$TFVARS_FILE"
  else
    echo "cognito_user_pool_id = \"$COGNITO_USER_POOL_ID\"" >> "$TFVARS_FILE"
  fi
  echo -e "${GREEN}  ✓ Updated cognito_user_pool_id${NC}"
fi

# Update athena_lambda_arn in tfvars
if [ -n "$ATHENA_LAMBDA_ARN" ]; then
  if grep -q "^athena_lambda_arn" "$TFVARS_FILE"; then
    sed -i.bak "s|^athena_lambda_arn.*|athena_lambda_arn = \"$ATHENA_LAMBDA_ARN\"|" "$TFVARS_FILE"
  else
    echo "athena_lambda_arn = \"$ATHENA_LAMBDA_ARN\"" >> "$TFVARS_FILE"
  fi
  echo -e "${GREEN}  ✓ Updated athena_lambda_arn${NC}"
fi

# Clean up sed backup files
rm -f "$TFVARS_FILE.bak"

echo ""
echo -e "${GREEN}Done! terraform.tfvars updated at: $TFVARS_FILE${NC}"
